spring.application.name=sale-management

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/sale-mgmt
spring.datasource.username=postgres
spring.datasource.password=Work@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
